on:
  push:
    branches:
      - main

jobs:
  run-continuous-integration:
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      wheels-artifact-name: w
  prepare-to-continuously-deliver:
    needs: [run-continuous-integration]
    runs-on: "ubuntu-latest"
    environment: pypi
    permissions:
      id-token: write  # required for trusted publishing
    steps:
      - name: "checkout repository so that the package is relesable"
        uses: actions/checkout@v5
      - name: "publish package to pypi on tagged commit"
        uses: pypa/gh-action-pypi-publish@release/v1
