on:
  workflow_call:
    inputs:
      wheels-artifact-name:
        required: true
        type: string

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v5
      - name: "install python 3.13"
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: "install tox for running tests"
        run: pip install tox
      # tox should be setup to use wheels/the .pkg directory for all python versions
      - name: "test package against python3.13"
        run: tox run -e python313
      - name: "upload binary wheel distribution files"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.wheels-artifact-name }}
          path: /.tox/.pkg/dist/