on:
  push:
    branches:
      - main

jobs:
  continuously-integrate:
    name: Continuous Integration
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      wheels-artifact-name: wheel-dists
  continuously-deliver:
    name: Continuous Delivery
    needs: [continuously-integrate]
    runs-on: "ubuntu-latest"
    environment: pypi
    permissions:
      id-token: write  # required for trusted publishing
    steps:
      - name: "checkout repository so that the package is releasable"
        uses: actions/checkout@v5
      - name: "download wheels directory artifact made in CI"
        uses: actions/download-artifact@v4
        with:
          name: wheel-dists
          # gh-action-pypi-publish searches for the wheels here
          path: dist/
      - name: "publish package to pypi on tagged commit"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
