on:
  push:
    branches:
      - main

jobs:
  prepare-to-continuously-deliver:
    runs-on: "ubuntu-latest"
    environment: pypi
    permissions:
      id-token: write  # required for trusted publishing
    steps:
      - name: "run through continuous integration"
        uses: ./.github/workflows/continuous-integration.yaml
      - name: "publish package to pypi on tagged commit"
        uses: pypa/gh-action-pypi-publish@release/v1
